version: '3.4'

services:
  test_bdd:
    image: ${DOCKER_REGISTRY-}testbdd
    build:
      context: .
      dockerfile: test_bdd/Dockerfile
    environment:
      ConnectionStrings__WebApiDatabase: Host=bdd;Database=postgres;Username=postgres;Password=example
  bdd:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080